# Generated by Django 5.2.7 on 2025-11-04 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisTabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('bunga_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('biaya_admin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Jenis Tabungan',
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantor_bank', models.CharField(max_length=100)),
                ('nomor_rekening', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabungan.jenistabungan')),
            ],
            options={
                'verbose_name_plural': 'Buku Tabungan',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], max_length=10)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_set', to='tabungan.buku')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-tanggal'],
            },
        ),
    ]
