# Generated by Django 5.2.7 on 2025-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
